receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp/aspire:
    endpoint: ${env:ASPIRE_ENDPOINT}
    headers:
      x-otlp-api-key: ${env:ASPIRE_API_KEY}
    tls:
      insecure: true
  zipkin:
    endpoint: http://host.docker.internal:9411/api/v2/spans
  otlp/jaeger:
    endpoint: http://host.docker.internal:5317
    tls:
      insecure: true
  otlp/tracelens:
    endpoint: http://host.docker.internal:6317
    tls:
      insecure: true
    
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/aspire, zipkin, otlp/jaeger, otlp/tracelens]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/aspire]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/aspire]
