using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.0.10000.0")]
[assembly: AssemblyFileVersionAttribute("1.0.10000.0")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2010")]
[assembly: AssemblyProductAttribute("CodeCampServerLite")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("1.0.10000.0")]

