//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderSystem.Shipping {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Shipping.IShippingService")]
    public interface IShippingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShippingService/ProcessOrderForShipping", ReplyAction="http://tempuri.org/IShippingService/ProcessOrderForShippingResponse")]
        bool ProcessOrderForShipping(int orderId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShippingServiceChannel : OrderSystem.Shipping.IShippingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShippingServiceClient : System.ServiceModel.ClientBase<OrderSystem.Shipping.IShippingService>, OrderSystem.Shipping.IShippingService {
        
        public ShippingServiceClient() {
        }
        
        public ShippingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShippingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ProcessOrderForShipping(int orderId) {
            return base.Channel.ProcessOrderForShipping(orderId);
        }
    }
}
