using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2013.01.16.1558")]
[assembly: AssemblyFileVersionAttribute("2013.01.16.1558")]
[assembly: AssemblyCopyrightAttribute("Copyright 2011")]
[assembly: AssemblyProductAttribute("CodeCampServerLite")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("2013.01.16.1558")]
